### ISSUE TITLE
Make the addon independent of the project window configuration

### ISSUE THREAD

**Issue by sortizu** [KoBeWi/Godot-Spritesheet-Generator#5]
Hello!
I've been using this addon recently and I want to thank @KoBeWi for this useful tool.
However, I found an unwanted behaviour that I think could be an obstacle for new users.
The problem is that is very difficult to use the addon when your project have the configuration for pixel art. When you work in this type of games, you use to change the strech mode to "viewport", use a very low resolution and disable the "resizable" option. Well, as the addon is an scene that you run, this settings are applied too. This can produce the following situation:

https://github.com/KoBeWi/Godot-Spritesheet-Generator/assets/93356841/1be61c16-1326-4148-81b4-fa3fcbe583f5

As you can see, with this settings it's impossible to see the rest of options showed in the panel, you can't even save your sprite sheet (which is the problem I deal the first time I used the addon). I know this is described in the README file, but I think this can be really annoying for your workflow in certain situations. If you are a new user who wants to use this addon because you found it in the asset library, you will need to change your settings every time or try to figure out how to set a different window configuration for the addon.
I don't mention the stand-alone version because many new users won't even know how to reach this GitHub repository.  I know it can seem like an unimportant problem and it focus on a small group of people, but it could be very valuable for the usability of this addon. My argument is that if it is possible to avoid problems for new users, then we should do it.
The way I solved this was the following:
```
func _ready():
	# Addon window configuration code
	get_window().size=Vector2(1100,700) #Or any other common resolution
	get_window().content_scale_mode=Window.CONTENT_SCALE_MODE_DISABLED
	get_window().unresizable=false
```
I used this code in the script attached to "SpriteSheetGenerator.tscn". I don't know if it is the best solution and it is very obvious, but I put it in case it helps.
Anyway, that's all. I would like to thank you again KoBeWi and also sorry for the bad english! :P

**Comment by KoBeWi** [comment]
Hi, my plan right now is to switch to stand-alone completely (the progress is [here](https://github.com/KoBeWi/Godot-Spritesheet-Generator/tree/secret_rework_branch)). It's possible to upload a whole projects to assetlib, so that's probably what I'll do once I finish the rework. I'm not sure yet if I want to keep the addon version.

**Comment by sortizu** [comment]
Oh, that sounds interesting. I honestly don't know what the difference is, but I hope this means you can have a different window setup for the tools you have in your projects. Thanks for your answer!
